services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
