name: Lint Code

on:
  push:
    branches:
      - "main"

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      # 5. Vérifier le serveur (Racine)
      - name: Run ESLint on all files with auto-fix
        run: npx eslint . --fix # npx permet d'exécuter les paquets sans les installer globalement, et --fix corrige automatiquement les problèmes détectés