name: Lint Code
on:
  push:
    branches:
      - "main"

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run ESLint client with auto-fix
        run: npm run lint:fix:client
      - name: Run ESLint server with auto-fix
        run: npm run lint:fix:server